version: '3.8'

services:
  mongo:
    container_name: mongo_container
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password321
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
    ports:
      - '27017:27017'

volumes:
  mongo:
    driver: local
